import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import test from "node:test";
import { renderMarkdown } from "../lib/render-markdown.mjs";

const projectRoot = new URL("../", import.meta.url);
const outputRoot = new URL("../public/", import.meta.url);

test("generates a real multi-page HTML blog", async () => {
  const [home, archive, about, files] = await Promise.all([
    readFile(new URL("index.html", outputRoot), "utf8"),
    readFile(new URL("articles/index.html", outputRoot), "utf8"),
    readFile(new URL("about/index.html", outputRoot), "utf8"),
    readdir(new URL("articles/", outputRoot)),
  ]);

  assert.match(home, /^<!doctype html>/i);
  assert.match(home, /Generated by scripts\/build-static\.mjs/);
  assert.match(home, /href="articles\/index\.html"/);
  assert.match(home, /href="about\/index\.html"/);
  assert.match(archive, /class="article-grid"/);
  assert.match(about, /你好，我是 Juice/);
  assert.deepEqual(files.sort(), [
    "ai-assistant-in-production.html",
    "index.html",
    "lessons-from-an-incident.html",
    "reliable-task-scheduler.html",
  ]);
});

test("every Markdown post produces a linked HTML article", async () => {
  const [markdownFiles, articleFiles, archive] = await Promise.all([
    readdir(new URL("content/posts/", projectRoot)),
    readdir(new URL("articles/", outputRoot)),
    readFile(new URL("articles/index.html", outputRoot), "utf8"),
  ]);

  const postPages = articleFiles.filter((file) => file !== "index.html");
  assert.equal(postPages.length, markdownFiles.length);

  for (const file of postPages) {
    const html = await readFile(new URL(`articles/${file}`, outputRoot), "utf8");
    assert.match(html, /^<!doctype html>/i);
    assert.match(html, /class="prose"/);
    assert.match(archive, new RegExp(`href="${file.replace(".", "\\.")}"`));
  }
});

test("allows the deployment host to be supplied by GitHub Pages", async () => {
  const generator = await readFile(
    new URL("scripts/build-static.mjs", projectRoot),
    "utf8",
  );

  assert.match(generator, /process\.env\.SITE_URL/);
  assert.match(generator, /\.replace\(\/\\\/\+\$\/,\s*""\)/);
});

test("renders fenced and inline code with syntax highlighting", async () => {
  const html = await renderMarkdown(
    "使用 `const` 声明变量。\n\n```js\nconst answer = 42;\n```",
  );

  assert.match(html, /<code>const<\/code>/);
  assert.match(html, /class="hljs language-js"/);
  assert.match(html, /hljs-keyword/);
  assert.match(html, /hljs-number/);
});

test("safely falls back to plain text for unknown code languages", async () => {
  const html = await renderMarkdown("```made-up\n<unsafe>\n```");

  assert.match(html, /class="hljs language-made-up"/);
  assert.match(html, /&lt;unsafe&gt;/);
});
