import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import test from "node:test";
import { renderMarkdown } from "../lib/render-markdown.mjs";

const projectRoot = new URL("../", import.meta.url);
const outputRoot = new URL("../public/", import.meta.url);

test("generates a real multi-page HTML blog", async () => {
  const [home, archive, about, files] = await Promise.all([
    readFile(new URL("index.html", outputRoot), "utf8"),
    readFile(new URL("articles/index.html", outputRoot), "utf8"),
    readFile(new URL("about/index.html", outputRoot), "utf8"),
    readdir(new URL("articles/", outputRoot)),
  ]);

  assert.match(home, /^<!doctype html>/i);
  assert.match(home, /Generated by scripts\/build-static\.mjs/);
  assert.match(home, /href="articles\/index\.html"/);
  assert.match(home, /href="about\/index\.html"/);
  assert.match(archive, /class="article-grid"/);
  assert.match(about, /你好，我是 Juice/);
  assert.deepEqual(files.sort(), [
    "agent-context-engineering.html",
    "ai-assistant-in-production.html",
    "arraylist-thread-safety.html",
    "baota-linux-project-deployment.html",
    "claude-code-architecture.html",
    "codex-skills-pr-review.html",
    "deepseek-harness-plugin-architecture.html",
    "distributed-transactions-seata.html",
    "foundation-architecture.html",
    "heavykeeper-topk.html",
    "high-concurrency-architecture.html",
    "http-https-nginx.html",
    "index.html",
    "java-concurrency-jmm.html",
    "java-concurrency-locks.html",
    "java-garbage-collectors.html",
    "java-locks-aqs.html",
    "java-parent-delegation.html",
    "java-thread-communication.html",
    "k8s-basics.html",
    "kafka-cluster-deployment.html",
    "kafka-installation-and-usage.html",
    "lessons-from-an-incident.html",
    "microservices-sentinel-avalanche-solutions.html",
    "mysql-recovery-record.html",
    "mysql-remote-connection-troubleshooting.html",
    "mysql-slow-sql-optimization.html",
    "rabbitmq-message-reliability.html",
    "rabbitmq-messaging-models.html",
    "rag-retrieval-augmented-generation.html",
    "redis-lua-scripts.html",
    "reliable-task-scheduler.html",
    "service-governance.html",
    "spring-boot-kafka-topic.html",
    "spring-cloud-gateway-custom-filters.html",
    "typescript-basics.html",
  ]);
});

test("every Markdown post produces a linked HTML article", async () => {
  const [markdownFiles, articleFiles, archive] = await Promise.all([
    readdir(new URL("content/posts/", projectRoot)),
    readdir(new URL("articles/", outputRoot)),
    readFile(new URL("articles/index.html", outputRoot), "utf8"),
  ]);

  const postPages = articleFiles.filter((file) => file !== "index.html");
  assert.equal(postPages.length, markdownFiles.length);

  for (const file of postPages) {
    const html = await readFile(new URL(`articles/${file}`, outputRoot), "utf8");
    assert.match(html, /^<!doctype html>/i);
    assert.match(html, /class="prose"/);
    assert.match(archive, new RegExp(`href="${file.replace(".", "\\.")}"`));
  }
});

test("allows the deployment host to be supplied by GitHub Pages", async () => {
  const generator = await readFile(
    new URL("scripts/build-static.mjs", projectRoot),
    "utf8",
  );

  assert.match(generator, /process\.env\.SITE_URL/);
  assert.match(generator, /\.replace\(\/\\\/\+\$\/,\s*""\)/);
});

test("renders fenced and inline code with syntax highlighting", async () => {
  const html = await renderMarkdown(
    "使用 `const` 声明变量。\n\n```js\nconst answer = 42;\n```",
  );

  assert.match(html, /<code>const<\/code>/);
  assert.match(html, /class="hljs language-js"/);
  assert.match(html, /hljs-keyword/);
  assert.match(html, /hljs-number/);
});

test("safely falls back to plain text for unknown code languages", async () => {
  const html = await renderMarkdown("```made-up\n<unsafe>\n```");

  assert.match(html, /class="hljs language-made-up"/);
  assert.match(html, /&lt;unsafe&gt;/);
});

test("renders D2 fences as responsive inline SVG diagrams", async () => {
  const html = await renderMarkdown(
    "```d2 博客发布流程\nMarkdown -> HTML -> Pages\n```",
    {
      renderD2: async (source) =>
        `<svg viewBox="0 0 100 50">
  <style><![CDATA[
    .node { fill: #fff; }
  ]]></style>
  <text class="node">${source}</text>
</svg>`,
    },
  );

  assert.match(html, /<figure class="d2-diagram" aria-label="博客发布流程">/);
  assert.match(html, /<div class="d2-diagram-canvas"><svg/);
  assert.match(html, /<figcaption>博客发布流程<\/figcaption>/);
  assert.match(html, /<style><!\[CDATA\[/);
  assert.match(html, /<text class="node">Markdown -> HTML -> Pages<\/text>/);
  assert.doesNotMatch(html, /<pre><code class="hljs language-d2"/);
  assert.doesNotMatch(html, /data-d2-placeholder/);
});

test("does not invoke D2 when an article has no D2 fence", async () => {
  const html = await renderMarkdown("普通文章内容。", {
    renderD2: async () => {
      throw new Error("不应调用 D2");
    },
  });

  assert.match(html, /<p>普通文章内容。<\/p>/);
});

test("gives repeated D2 diagrams distinct deterministic SVG salts", async () => {
  const salts = [];
  const html = await renderMarkdown(
    "```d2\na -> b\n```\n\n```d2\na -> b\n```",
    {
      renderD2: async (_source, options) => {
        salts.push(options.salt);
        return `<svg data-salt="${options.salt}"></svg>`;
      },
    },
  );

  assert.equal(salts.length, 2);
  assert.notEqual(salts[0], salts[1]);
  assert.match(html, new RegExp(`data-salt="${salts[0]}"`));
  assert.match(html, new RegExp(`data-salt="${salts[1]}"`));
});
