import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import test from "node:test";

const projectRoot = new URL("../", import.meta.url);
const outputRoot = new URL("../public/", import.meta.url);

test("generates a real multi-page HTML blog", async () => {
  const [home, archive, about, files] = await Promise.all([
    readFile(new URL("index.html", outputRoot), "utf8"),
    readFile(new URL("articles/index.html", outputRoot), "utf8"),
    readFile(new URL("about/index.html", outputRoot), "utf8"),
    readdir(new URL("articles/", outputRoot)),
  ]);

  assert.match(home, /^<!doctype html>/i);
  assert.match(home, /Generated by scripts\/build-static\.mjs/);
  assert.match(home, /href="articles\/index\.html"/);
  assert.match(home, /href="about\/index\.html"/);
  assert.match(archive, /class="article-grid"/);
  assert.match(about, /你好，我是 Juice/);
  assert.deepEqual(files.sort(), [
    "ai-assistant-in-production.html",
    "index.html",
    "lessons-from-an-incident.html",
    "reliable-task-scheduler.html",
  ]);
});

test("every Markdown post produces a linked HTML article", async () => {
  const [markdownFiles, articleFiles, archive] = await Promise.all([
    readdir(new URL("content/posts/", projectRoot)),
    readdir(new URL("articles/", outputRoot)),
    readFile(new URL("articles/index.html", outputRoot), "utf8"),
  ]);

  const postPages = articleFiles.filter((file) => file !== "index.html");
  assert.equal(postPages.length, markdownFiles.length);

  for (const file of postPages) {
    const html = await readFile(new URL(`articles/${file}`, outputRoot), "utf8");
    assert.match(html, /^<!doctype html>/i);
    assert.match(html, /class="prose"/);
    assert.match(archive, new RegExp(`href="${file.replace(".", "\\.")}"`));
  }
});
