import { readFile, readdir, mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";
import { marked } from "marked";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const postsDirectory = path.join(root, "content", "posts");
const outputDirectories = [path.join(root, "public")];
const defaultSiteUrl = "https://juice-notes.yellow-coin-6347.chatgpt.site";
const siteUrl = (process.env.SITE_URL || defaultSiteUrl).replace(/\/+$/, "");

const escapeHtml = (value = "") =>
  String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");

const requiredFields = [
  "title",
  "slug",
  "publishedAt",
  "date",
  "category",
  "excerpt",
  "readTime",
];

async function loadPosts() {
  const files = (await readdir(postsDirectory))
    .filter((file) => file.endsWith(".md"))
    .sort();

  const posts = await Promise.all(
    files.map(async (file) => {
      const source = await readFile(path.join(postsDirectory, file), "utf8");
      const { data, content } = matter(source);
      const missing = requiredFields.filter((field) => !data[field]);

      if (missing.length > 0) {
        throw new Error(`${file} 缺少字段：${missing.join("、")}`);
      }

      if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(data.slug)) {
        throw new Error(`${file} 的 slug 只能包含小写字母、数字和连字符`);
      }

      return {
        ...data,
        sourceFile: file,
        html: await marked.parse(content, { gfm: true }),
      };
    }),
  );

  const slugs = new Set();
  for (const post of posts) {
    if (slugs.has(post.slug)) {
      throw new Error(`发现重复 slug：${post.slug}`);
    }
    slugs.add(post.slug);
  }

  return posts.sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));
}

function relativeLinks(depth) {
  const prefix = depth === 0 ? "" : "../";
  return {
    prefix,
    home: `${prefix}index.html`,
    articles: `${prefix}articles/index.html`,
    about: `${prefix}about/index.html`,
  };
}

function layout({ title, description, active, depth, canonicalPath, content }) {
  const links = relativeLinks(depth);
  const navItem = (key, href, label) =>
    `<a${active === key ? ' class="active" aria-current="page"' : ""} href="${href}">${label}</a>`;

  return `<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="${escapeHtml(description)}" />
    <meta property="og:title" content="${escapeHtml(title)}" />
    <meta property="og:description" content="${escapeHtml(description)}" />
    <meta property="og:image" content="${siteUrl}/og.png" />
    <meta property="og:type" content="website" />
    <link rel="canonical" href="${siteUrl}${canonicalPath}" />
    <link rel="stylesheet" href="${links.prefix}assets/styles.css" />
    <title>${escapeHtml(title)}</title>
  </head>
  <body>
    <!-- Generated by scripts/build-static.mjs. Edit content/, templates in this script, or app/globals.css instead. -->
    <a class="skip-link" href="#content">跳到主要内容</a>
    <header class="site-header">
      <a class="brand" href="${links.home}" aria-label="JUICE. 首页">JUICE<span class="brand-dot">.</span></a>
      <nav class="main-nav" aria-label="主导航">
        ${navItem("home", links.home, "首页")}
        ${navItem("articles", links.articles, "文章")}
        ${navItem("about", links.about, "关于")}
      </nav>
      <a class="header-cta" href="${links.about}">认识 Juice <span aria-hidden="true">↗</span></a>
    </header>
    ${content}
    <footer class="site-footer">
      <a class="brand footer-brand" href="${links.home}">JUICE<span class="brand-dot">.</span></a>
      <p>把想明白的事，认真写下来。</p>
      <p>© 2026 Juice</p>
    </footer>
  </body>
</html>
`;
}

function postCard(post, depth, number) {
  const href = depth === 0
    ? `articles/${post.slug}.html`
    : `${post.slug}.html`;

  return `<article class="post">
    <div class="post-number" aria-hidden="true">${String(number).padStart(2, "0")}</div>
    <div class="post-meta">
      <span class="post-category">${escapeHtml(post.category)}</span>
      <time datetime="${escapeHtml(post.publishedAt)}">${escapeHtml(post.date)}</time>
    </div>
    <h3><a href="${href}">${escapeHtml(post.title)}</a></h3>
    <p>${escapeHtml(post.excerpt)}</p>
    <div class="post-footer">
      <span>${escapeHtml(post.readTime)}</span>
      <a href="${href}" aria-label="阅读文章：${escapeHtml(post.title)}">阅读文章 <span aria-hidden="true">→</span></a>
    </div>
  </article>`;
}

function hero() {
  return `<section class="hero" aria-labelledby="hero-title">
    <div class="hero-copy">
      <p class="eyebrow"><span aria-hidden="true"></span>一杯新鲜思考</p>
      <h1 id="hero-title">把复杂问题，<br />写成<span class="highlight">清晰答案</span></h1>
      <p class="hero-description">关于工程、AI 与持续成长的个人记录。<br />不追逐噪声，只分享那些真正想明白的事。</p>
      <div class="hero-actions">
        <a class="button button-primary" href="articles/index.html">开始阅读 <span aria-hidden="true">→</span></a>
        <a class="text-link" href="about/index.html">关于这个博客 <span aria-hidden="true">→</span></a>
      </div>
    </div>
    <div class="hero-art" aria-hidden="true">
      <div class="sun"></div><div class="leaf leaf-one"></div><div class="leaf leaf-two"></div>
      <div class="glass"><div class="juice"><span class="bubble bubble-one"></span><span class="bubble bubble-two"></span><span class="bubble bubble-three"></span></div><div class="straw"></div><div class="orange-slice"></div></div>
      <div class="note"><span>今日鲜榨</span><strong>Stay curious.</strong><em>— Juice</em></div>
      <span class="spark spark-one">✦</span><span class="spark spark-two">✦</span>
    </div>
  </section>`;
}

function homePage(posts) {
  const cards = posts.slice(0, 3).map((post, index) => postCard(post, 0, index + 1)).join("\n");
  return layout({
    title: "JUICE. — 把复杂问题，写成清晰答案",
    description: "Juice 的个人博客，记录工程、AI 与持续成长。",
    active: "home",
    depth: 0,
    canonicalPath: "/index.html",
    content: `<main id="content">
      ${hero()}
      <section class="articles-section" aria-labelledby="articles-title">
        <div class="section-heading"><div><p class="eyebrow"><span aria-hidden="true"></span>最近更新</p><h2 id="articles-title">新鲜文章</h2></div><a class="text-link all-posts" href="articles/index.html">查看全部 <span aria-hidden="true">↗</span></a></div>
        <div class="posts">${cards}</div>
      </section>
      <section class="about-section" aria-labelledby="about-title">
        <div class="about-mark" aria-hidden="true">J<span>.</span></div>
        <div class="about-copy"><p class="eyebrow"><span aria-hidden="true"></span>关于我</p><h2 id="about-title">你好，我是 Juice。</h2><p>我喜欢把复杂系统拆成清晰的结构，也喜欢记录技术之外那些让人持续成长的瞬间。这里没有标准答案，只有经过实践、复盘和重新思考后的个人经验。</p></div>
        <div class="topics" aria-label="博客主题"><span>工程实践</span><span>AI 探索</span><span>生活随笔</span></div>
      </section>
    </main>`,
  });
}

function articlesPage(posts) {
  const cards = posts.map((post, index) => postCard(post, 1, index + 1)).join("\n");
  return layout({
    title: "全部文章 — JUICE.",
    description: "Juice 关于工程、AI 与持续成长的全部文章。",
    active: "articles",
    depth: 1,
    canonicalPath: "/articles/index.html",
    content: `<main id="content" class="page-main">
      <section class="page-intro"><p class="eyebrow"><span aria-hidden="true"></span>文章归档</p><h1>所有认真想过的事</h1><p>工程实践、AI 探索与生活随笔。按时间倒序，持续更新。</p></section>
      <section class="article-grid" aria-label="全部文章">${cards}</section>
    </main>`,
  });
}

function aboutPage() {
  return layout({
    title: "关于 Juice — JUICE.",
    description: "认识 Juice，以及这个博客为什么存在。",
    active: "about",
    depth: 1,
    canonicalPath: "/about/index.html",
    content: `<main id="content" class="page-main">
      <section class="about-page">
        <div class="about-mark about-mark-large" aria-hidden="true">J<span>.</span></div>
        <div class="about-page-copy"><p class="eyebrow"><span aria-hidden="true"></span>关于我</p><h1>你好，我是 Juice。</h1><p>我喜欢把复杂系统拆成清晰的结构，也喜欢记录技术之外那些让人持续成长的瞬间。</p><p>这个博客是我的长期笔记：不追逐噪声，不堆砌术语，只保留那些经过实践、复盘和重新思考之后，仍然值得写下来的内容。</p><div class="topics topics-inline" aria-label="博客主题"><span>工程实践</span><span>AI 探索</span><span>生活随笔</span></div></div>
      </section>
    </main>`,
  });
}

function postPage(post) {
  return layout({
    title: `${post.title} — JUICE.`,
    description: post.excerpt,
    active: "articles",
    depth: 1,
    canonicalPath: `/articles/${post.slug}.html`,
    content: `<main id="content" class="article-page">
      <article class="article-shell">
        <a class="back-link" href="index.html">← 返回文章列表</a>
        <header class="article-header">
          <div class="post-meta"><span class="post-category">${escapeHtml(post.category)}</span><time datetime="${escapeHtml(post.publishedAt)}">${escapeHtml(post.date)}</time><span>${escapeHtml(post.readTime)}</span></div>
          <h1>${escapeHtml(post.title)}</h1>
          <p>${escapeHtml(post.excerpt)}</p>
        </header>
        <div class="prose">${post.html}</div>
        <footer class="article-end"><span>✦</span><p>感谢阅读。继续保持好奇。</p><a href="index.html">阅读更多文章 →</a></footer>
      </article>
      <section class="giscus-comments" aria-label="文章评论">
        <script src="https://giscus.app/client.js"
          data-repo="yuhaohub/blog-comments"
          data-repo-id="R_kgDOTksiXg"
          data-category="Announcements"
          data-category-id="DIC_kwDOTksiXs4DCDpw"
          data-mapping="pathname"
          data-strict="0"
          data-reactions-enabled="1"
          data-emit-metadata="0"
          data-input-position="top"
          data-theme="${siteUrl}/assets/giscus-theme.css"
          data-lang="zh-CN"
          data-loading="lazy"
          crossorigin="anonymous"
          async>
        </script>
      </section>
    </main>`,
  });
}

async function writeGenerated(relativePath, content) {
  await Promise.all(
    outputDirectories.map(async (directory) => {
      const destination = path.join(directory, relativePath);
      await mkdir(path.dirname(destination), { recursive: true });
      await writeFile(destination, content, "utf8");
    }),
  );
}

async function build() {
  const posts = await loadPosts();
  const css = await readFile(path.join(root, "app", "globals.css"), "utf8");

  for (const directory of outputDirectories) {
    await rm(path.join(directory, "articles"), { recursive: true, force: true });
    await rm(path.join(directory, "about"), { recursive: true, force: true });
  }

  await writeGenerated("assets/styles.css", css);
  await writeGenerated("index.html", homePage(posts));
  await writeGenerated("articles/index.html", articlesPage(posts));
  await writeGenerated("about/index.html", aboutPage());
  await Promise.all(
    posts.map((post) =>
      writeGenerated(`articles/${post.slug}.html`, postPage(post)),
    ),
  );

  console.log(`Generated ${posts.length + 3} HTML pages from ${posts.length} Markdown posts.`);
}

await build();
